// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var update_loc;
    update_loc = function() {
      var address;
      address = $('#id_address').val();
      $.get('/geocode/?addr=' + address, function(data) {
        var loc;
        if (data === "-1" || data === "-2") {
          $('#id_locationX').val('0');
          return $('#id_locationY').val('0');
        } else {
          loc = data.split('/');
          $('#id_locationX').val(loc[0]);
          return $('#id_locationY').val(loc[1]);
        }
      });
      return false;
    };
    return $("#id_address").change(update_loc);
  });

}).call(this);
